name: docker_build

on: [pull_request]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag macintoshprime/kubectl:v1.17

  push:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p '${{ secrets.DOCKER_PASS }}'

    - name: Push Image
      run: docker push macintoshprime/kubectl:v1.17